### ISSUE TITLE
Request for Guidance about HCPLifespan2BIDS

### ISSUE THREAD

**Issue by zhitao-guo** [ellisdg/HCPLifespan2BIDS#2]
Thank you for your code very much.
I encountered some problems when I ran the processing HCP Young Adult dataset following the instructions.
- I list the structure of the data files for subject 100307 as follows. There seems to be a bug when dealing with T1w and T2w image if “t1w_use_derived” and “t2w_use_derived” are set. The T2w image will not be processed because str “T1w” always in the path of T2w image.
```
100307/
└── unprocessed
    └── 3T
        ├── rfMRI_REST1_LR
        │   ├── 100307_3T_rfMRI_REST1_LR.nii.gz
        │   ├── 100307_3T_rfMRI_REST1_LR_SBRef.nii.gz
        │   ├── 100307_3T_SpinEchoFieldMap_LR.nii.gz
        │   ├── 100307_3T_SpinEchoFieldMap_RL.nii.gz
        │   └── LINKED_DATA
        │       └── PHYSIO
        │           └── 100307_3T_rfMRI_REST1_LR_Physio_log.txt
        ├── rfMRI_REST1_RL
        │   ├── 100307_3T_rfMRI_REST1_RL.nii.gz
        │   ├── 100307_3T_rfMRI_REST1_RL_SBRef.nii.gz
        │   ├── 100307_3T_SpinEchoFieldMap_LR.nii.gz
        │   ├── 100307_3T_SpinEchoFieldMap_RL.nii.gz
        │   └── LINKED_DATA
        │       └── PHYSIO
        │           └── 100307_3T_rfMRI_REST1_RL_Physio_log.txt
        ├── rfMRI_REST2_LR
        │   ├── 100307_3T_rfMRI_REST2_LR.nii.gz
        │   ├── 100307_3T_rfMRI_REST2_LR_SBRef.nii.gz
        │   ├── 100307_3T_SpinEchoFieldMap_LR.nii.gz
        │   ├── 100307_3T_SpinEchoFieldMap_RL.nii.gz
        │   └── LINKED_DATA
        │       └── PHYSIO
        │           └── 100307_3T_rfMRI_REST2_LR_Physio_log.txt
        ├── rfMRI_REST2_RL
        │   ├── 100307_3T_rfMRI_REST2_RL.nii.gz
        │   ├── 100307_3T_rfMRI_REST2_RL_SBRef.nii.gz
        │   ├── 100307_3T_SpinEchoFieldMap_LR.nii.gz
        │   ├── 100307_3T_SpinEchoFieldMap_RL.nii.gz
        │   └── LINKED_DATA
        │       └── PHYSIO
        │           └── 100307_3T_rfMRI_REST2_RL_Physio_log.txt
        └── T1w
            ├── T1w_acpc_dc.nii.gz
            └── T2w_acpc_dc.nii.gz

```
- For sMRI data, could you please explain the reason of using T1/2w_acpc_dc.nii.gz file for input of fmriPrep instead of T1/2w_acpc_dc_restore.nii.gz?
- For hcpya-sidecar files, it seems that there is no single band sidecar files. Is it necessary for preprocessing? And I am not familiar with the internal steps of fmriPrep, I wonder whether the information in the sidecar files are enough for fmriPrep.

Thank you very much for your time and assistance. I sincerely receive your response.

**Comment by ellisdg** [comment]
Thank you for your comments and questions!

> For sMRI data, could you please explain the reason of using T1/2w_acpc_dc.nii.gz file for input of fmriPrep instead of T1/2w_acpc_dc_restore.nii.gz?

The "restore" file has been bias field corrected. fmriprep does its own biasfield correction, so there is no need to input the pre-corrected image.

> For hcpya-sidecar files, it seems that there is no single band sidecar files. Is it necessary for preprocessing? And I am not familiar with the internal steps of fmriPrep, I wonder whether the information in the sidecar files are enough for fmriPrep.

Looking at my bids folder for the HCPYA, I do have json sidecar files for the sbref images. So I'm not sure why they didn't get created. For fmriprep, you could ignore the sbref images, as last time I checked they were not used in processing.

**Comment by ellisdg** [comment]
> There seems to be a bug when dealing with T1w and T2w image if “t1w_use_derived” and “t2w_use_derived” are set. The T2w image will not be processed because str “T1w” always in the path of T2w image.

That makes sense, and I am confused as to how it worked for me when I ran it. I suppose the solution would be to change the elif statements in lines 140 and 147 in [lifepsan.py](https://github.com/ellisdg/HCPLifespan2BIDS/blob/master/lifespan.py) to something along the lines of 
```(python)
elif "T1w" in os.path.basename(image_file):
```
so that way it doesn't get tripped up by the folder name.

**Comment by zhitao-guo** [comment]
Hi ellisdg,
Thanks for your detailed reply!

> The "restore" file has been bias field corrected. fmriprep does its own biasfield correction, so there is no need to input the pre-corrected image.

Thank you for your explanation. I would like to ask if you could guide me on how to disable the bias field correction in fMRIPrep. Maybe my collaborators are interested in using the HCP's own bias field correction method instead.

> Looking at my bids folder for the HCPYA, I do have json sidecar files for the sbref images. So I'm not sure why they didn't get created. For fmriprep, you could ignore the sbref images, as last time I checked they were not used in processing.

Thank you for your assistance. I have thoroughly checked the sidecar files under `hcpya-sidecars` , but I wasn't able to locate the sbref file. Could you please help me with this?

I encountered a warning message "You must define 'EchoTime' for this file." when I uded the [BIDS Validator](https://bids-standard.github.io/bids-validator/).  I think this is caused by the lack of EchoTime field in the epi.json sidecar. But there is no warning when I used the [previous version](https://bids-standard.github.io/bids-validator/legacy). Can I add `"EchoTime": 0.0331` to the epi.json sidecar, or ignore the warning?

Thanks again~

**Comment by ellisdg** [comment]
> I would like to ask if you could guide me on how to disable the bias field correction in fMRIPrep. 

I don't know if that is possible, but you can check the fmriprep documentation:
[https://fmriprep.org/en/stable/usage.html](https://fmriprep.org/en/stable/usage.html)

For the EPI echo time, we can look at the acquisition parameters reported by the HCP:
[https://humanconnectome.org/storage/app/media/documentation/s1200/HCP_S1200_Release_Appendix_I.pdf](https://humanconnectome.org/storage/app/media/documentation/s1200/HCP_S1200_Release_Appendix_I.pdf)

Page 39 says that the "TE" or echo time is 58 ms or 0.058 s.

> I have thoroughly checked the sidecar files under hcpya-sidecars , but I wasn't able to locate the sbref file. Could you please help me with this?

Does BIDS require a sidecar for sbref files? Looking back at what I did was to put "IntendedFor" and the relevant filename in the sidecar. You can find information on "IntendedFor" in the BIDS spec. (Note that fmriprep requires relative filepaths rather than BIDS uris).

**Comment by zhitao-guo** [comment]
Thanks for your reply.

I'm sorry for the ambiguous description. After running the code, the final sbref sidecar files like the following and lack the imaging parameters such as "RepetitionTime", "EchoTime". My confusion is that whether these imaging parameters are necessary, maybe not?

```
{
    "IntendedFor": "func/sub-100307_task-rest_dir-LR_run-1_bold.nii.gz",
    "TaskName": "rest"
}
```
Many thanks.

**Comment by ellisdg** [comment]
I don't think that other fields are necessary for the sbref files. I tested it with a bids validator and it didn't throw any warning or error for the sbref files.

**Comment by zhitao-guo** [comment]
Thanks very much.
